name: Validate Component JSON

on: [push]
jobs:
  validate_configurations:
    name: Validate All Components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Validate Pin Components
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: components/pin/schema.json
          json_path_pattern: components/pin/.*/definition.json$
